<?php

use Magento\Framework\Escaper;
use GabrielStarling\ProductReviews\Block\Product\ReviewsList\Toolbar;

/**
 * @var Toolbar $block
 * @var Escaper $escaper
 */
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter">
        <?= $escaper->escapeHtml(__('Sort By')) ?>
    </label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <option value="<?= $escaper->escapeHtmlAttr($_key) ?>" <?php if ($block->isOrderCurrent($_key)): ?>
                    selected="selected" <?php endif; ?>>
                <?= $escaper->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?php if ($block->getCurrentDirection() == 'asc'): ?>
        <a value="desc" class="action sorter-action sort-asc">
        </a>
    <?php else: ?>
        <a value="asc" class="action sorter-action sort-desc">
        </a>
    <?php endif; ?>
</div>